# Generated by Django 4.2 on 2025-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='animals/')),
                ('habitat', models.CharField(blank=True, max_length=100)),
                ('is_animal_of_the_day', models.BooleanField(default=False)),
            ],
        ),
    ]
